// -- AUTOGENERATED - DO NOT EDIT --

import { Token, Type } from './token';

export abstract class Expr {}
export class Assign extends Expr {
  name: Token | ArrayAccess;
  value: Expr;
  constructor(name: Token | ArrayAccess, value: Expr) { 
    super();
    this.name = name;
    this.value = value;
  }
}
export class Binary extends Expr {
  left: Expr;
  operator: Token;
  right: Expr;
  constructor(left: Expr, operator: Token, right: Expr) { 
    super();
    this.left = left;
    this.operator = operator;
    this.right = right;
  }
}
export class Call extends Expr {
  callee: Expr;
  paren: Token;
  args: Expr[];
  constructor(callee: Expr, paren: Token, args: Expr[]) { 
    super();
    this.callee = callee;
    this.paren = paren;
    this.args = args;
  }
}
export class Grouping extends Expr {
  expression: Expr;
  constructor(expression: Expr) { 
    super();
    this.expression = expression;
  }
}
export class Literal extends Expr {
  value: any;
  type: "string" | "boolean" | "number" | "null";
  constructor(value: any, type: "string" | "boolean" | "number" | "null") { 
    super();
    this.value = value;
    this.type = type;
  }
}
export class ArrayLiteral extends Expr {
  elements: Expr[];
  type: Type;
  size: Expr;
  constructor(elements: Expr[], type: Type, size: Expr) { 
    super();
    this.elements = elements;
    this.type = type;
    this.size = size;
  }
}
export class Logical extends Expr {
  left: Expr;
  operator: Token;
  right: Expr;
  constructor(left: Expr, operator: Token, right: Expr) { 
    super();
    this.left = left;
    this.operator = operator;
    this.right = right;
  }
}
export class Unary extends Expr {
  operator: Token;
  right: Expr;
  constructor(operator: Token, right: Expr) { 
    super();
    this.operator = operator;
    this.right = right;
  }
}
export class Variable extends Expr {
  name: Token;
  constructor(name: Token) { 
    super();
    this.name = name;
  }
}
export class ArrayAccess extends Expr {
  name: Token;
  index: Expr;
  constructor(name: Token, index: Expr) { 
    super();
    this.name = name;
    this.index = index;
  }
}
