// -- AUTOGENERATED - DO NOT EDIT --

import { Token } from './token';

import { Expr } from './expr';

export abstract class Stmt {
  abstract accept<R>(visitor: Visitor<R>): R;
}
export interface Visitor<R> {
  visit(stmt: Stmt): R;
}
export class Block extends Stmt {
  statements: Stmt[];
  constructor(statements: Stmt[]) { 
    super();
    this.statements = statements;
  }
  accept<R>(visitor: Visitor<R>): R {
    return visitor.visit(this);
  }
}
export class Expression extends Stmt {
  expression: Expr;
  constructor(expression: Expr) { 
    super();
    this.expression = expression;
  }
  accept<R>(visitor: Visitor<R>): R {
    return visitor.visit(this);
  }
}
export class Func extends Stmt {
  name: Token;
  params: Token[];
  body: Stmt[];
  returnType: Token | null;
  constructor(name: Token, params: Token[], body: Stmt[], returnType: Token | null) { 
    super();
    this.name = name;
    this.params = params;
    this.body = body;
    this.returnType = returnType;
  }
  accept<R>(visitor: Visitor<R>): R {
    return visitor.visit(this);
  }
}
export class If extends Stmt {
  condition: Expr;
  thenBranch: Stmt;
  elseBranch: Stmt | null;
  constructor(condition: Expr, thenBranch: Stmt, elseBranch: Stmt | null) { 
    super();
    this.condition = condition;
    this.thenBranch = thenBranch;
    this.elseBranch = elseBranch;
  }
  accept<R>(visitor: Visitor<R>): R {
    return visitor.visit(this);
  }
}
export class Return extends Stmt {
  keyword: Token;
  value: Expr | null;
  constructor(keyword: Token, value: Expr | null) { 
    super();
    this.keyword = keyword;
    this.value = value;
  }
  accept<R>(visitor: Visitor<R>): R {
    return visitor.visit(this);
  }
}
export class Let extends Stmt {
  name: Token;
  initializer: Expr;
  constructor(name: Token, initializer: Expr) { 
    super();
    this.name = name;
    this.initializer = initializer;
  }
  accept<R>(visitor: Visitor<R>): R {
    return visitor.visit(this);
  }
}
export class While extends Stmt {
  condition: Expr;
  body: Stmt;
  constructor(condition: Expr, body: Stmt) { 
    super();
    this.condition = condition;
    this.body = body;
  }
  accept<R>(visitor: Visitor<R>): R {
    return visitor.visit(this);
  }
}
